# منظومة Render لنشر مشروع إصدار البطاقات والشهادات

services:
  # خدمة الواجهة الخلفية (API)
  - type: web
    name: certificates-api
    env: node
    repo: https://github.com/mahm1oud/server # تحديث هذا مع مستودع GitHub الخاص بك
    region: ohio
    buildCommand: |
      npm install
      # نسخ ملف vite.config.ts الى المجلد الحالي لحل مشكلة الاستيراد
      cp -f vite.config.ts server/
      # بناء المشروع
      npm run build:server
    startCommand: node server/dist/index.js
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: SESSION_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: certificates-db
          property: connectionString
      - key: ALLOWED_ORIGINS
        sync: false
    autoDeploy: false
    disk:
      name: uploads
      mountPath: /app/uploads
      sizeGB: 5

  # خدمة الواجهة الأمامية (Website)
  - type: web
    name: certificates-web
    env: static
    buildCommand: cd client && npm install && npm run build
    staticPublishPath: ./client/dist
    envVars:
      - key: VITE_API_URL
        sync: false # يحتاج إلى تعيين عنوان URL للخادم بعد النشر
    autoDeploy: false
    headers:
      - path: /*
        name: Cache-Control
        value: max-age=86400

databases:
  - name: certificates-db
    region: ohio
    databaseName: certificates
    ipAllowList: []

diskVolumes:
  - name: uploads
    sizeGB: 5